//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LINQAssignmentEntities : DbContext
    {
        public LINQAssignmentEntities()
            : base("name=LINQAssignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT> DEPTs { get; set; }
        public virtual DbSet<EMP> EMPs { get; set; }
    
        public virtual ObjectResult<JobWiseDetails_Result> JobWiseDetails(string job, Nullable<int> count, Nullable<decimal> mxSal, Nullable<decimal> mnSal)
        {
            var jobParameter = job != null ?
                new ObjectParameter("job", job) :
                new ObjectParameter("job", typeof(string));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            var mxSalParameter = mxSal.HasValue ?
                new ObjectParameter("mxSal", mxSal) :
                new ObjectParameter("mxSal", typeof(decimal));
    
            var mnSalParameter = mnSal.HasValue ?
                new ObjectParameter("mnSal", mnSal) :
                new ObjectParameter("mnSal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JobWiseDetails_Result>("JobWiseDetails", jobParameter, countParameter, mxSalParameter, mnSalParameter);
        }
    }
}
